### ISSUE TITLE
change messages.android.com to messages.google.com/web/

### ISSUE THREAD

**Issue by kaylenef** [meetfranz/franz#1383]
**Is your feature request related to a problem? Please describe.**
Messages for web is now located at host google.com instead of android.com. The default url needs to be changed.

**Describe the solution you'd like**
change messages.android.com to messages.google.com/web/

**Additional context**
![image](https://user-images.githubusercontent.com/47119298/55638003-78c4b380-5783-11e9-9dd6-1768acdc8b81.png)

**Comment by vishnureddy17** [comment]
Looks like it was fixed at https://github.com/dweinber/franz-recipe-android-messages/commit/9aa499683ff0acba2325c06223c82060503ae1f3

**Comment by RavHilton** [comment]
Will this fix be in 5.0.2?  When can we expect this service fix to be released?

**Comment by vishnureddy17** [comment]
Try deleting the service and re-adding it.

**Comment by kaylenef** [comment]
I've tried deleting the service multiple times _and_ deleting Franz and re-installing. Still getting that "Find us at messages.google.com/web and bookmark it for next time"

**Comment by dfrazao** [comment]
Have the same issue, tried deleting and re-adding it and didn't work...

**Comment by jaminroe** [comment]
Any updates on this? Surprised this isn't a priority.
