### ISSUE TITLE
Missing service icons

### ISSUE THREAD

**Issue by ifigueroap** [meetfranz/franz#1913]
**Describe the bug**
I recently installed Franz 5.5.0 on Windows 10, and the service icons are all but missing!
The issue still happens if I delete and re-add the services...

**To Reproduce**
1. Install Franz
2. Login to account
3. See that icons are missing

**Expected behavior**
I expect to see the service icons

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
![image](https://user-images.githubusercontent.com/508183/96709347-f6a1dd00-1370-11eb-82ad-da277e14a77e.png)

**Comment by promarcel** [comment]
I'm also affected by this issue, custom icons disappeared.

Any news @ifigueroap? Do you still expect this issue?

**Comment by ifigueroap** [comment]
@promarcel In my case it is the default icons that are missing... I had to download the logos from the net to make it work :(

**Comment by promarcel** [comment]
Really weired, in my case the default icons (from default services, 
exclude custom websites) are missing, even delete them and upload a own 
seems not to be work.

**Comment by promarcel** [comment]
@ifigueroap For me, I could figure out the issue is #1951.

**Comment by benguaraldi** [comment]
I have posted a temporary solution for this at:
https://github.com/meetfranz/franz/issues/1951#issuecomment-752764796

**Comment by benguaraldi** [comment]
Per @promarcel in #1951, this should be working now.

**Comment by ziegenberg** [comment]
I guess it can be closed now.

**Comment by ifigueroap** [comment]
Great news!
How can I trigger the reload of the icons? I just deleted the custom icons and still got blank ones :/

**Comment by benguaraldi** [comment]
@ifigueroap I rebooted the app and it worked for me.

**Comment by ifigueroap** [comment]
@benguaraldi thanks... Sadly it's still not working... I just:

* Uninstalled the app
* deleted the AppData/Roaming/Franz folder
* Reinstalled& Log into account

But still no icons.. is there any command I can run to check whether is a network issue on my side?

**Comment by benguaraldi** [comment]
@ifigueroap Can you go to https://cdn.franzinfra.com?  I was getting a certificate error there before.

**Comment by ifigueroap** [comment]
> @ifigueroap Can you go to https://cdn.franzinfra.com? I was getting a certificate error there before.

![image](https://user-images.githubusercontent.com/508183/103550967-690e5d80-4e88-11eb-9b44-258e49ef90b8.png)

![image](https://user-images.githubusercontent.com/508183/103551004-7592b600-4e88-11eb-924d-2692342d6960.png)

**Comment by benguaraldi** [comment]
@ifigueroap Interesting.  I guess your problem wasn't related to #1951, then, and probably isn't fixed.  Sorry!

**Comment by ifigueroap** [comment]
Hi, I'm doing some follow up research on this issue, as it is still not solved for me :(
By inspecting the developer tools view, I think I managed to pinpoint the issue...

When Franz is loading the icons for each service, it performes a file request, as in the screenshot below:

![image](https://user-images.githubusercontent.com/508183/108503341-f835d000-7292-11eb-9565-be2e3a48314c.png)

However, in the preview this shows as:

![image](https://user-images.githubusercontent.com/508183/108503365-071c8280-7293-11eb-9594-c493719e4481.png)

So I suspect this is due to the strange `content-type: document/ConceptDrawDIAGRAM` header...

**Comment by ifigueroap** [comment]
Well, I just changed the Windows Registry ("HKEY_CLASSES_ROOT\.svg"), and changed the following:

  * Content Type: from `document/ConceptDrawDIAGRAM` to `image/svg+xml`
  * PerceivedType: from `document` to `image`
  * (Predetermined): from `ConceptDRAW document` to `SVG`

after that, I reloaded Franz and the default icons finally appeared! Finally!

Still, in my opinion this should merit a small fix when validating the load of the icons, as it is very upsetting to use Franz without the sidebar icons :(

Best regards!
