### ISSUE TITLE
Notification not showing up on Taskbar

### ISSUE THREAD

**Issue by Endofdays2018** [meetfranz/franz#672]
I have franz app pinned to my taskbar, up until now when I received a message a notification would show up. Now all of a sudden it doesn't. I re-installed franz but still same issue occurs. See screenshot below. you'll see Franz app icon but now message notification

![scrnshot](https://user-images.githubusercontent.com/36317512/36057048-ce4f32ae-0dd7-11e8-8581-f52c550e4ac0.JPG)

Can anyone help?

**Comment by haraldox** [comment]
@Endofdays2018 what services do you have installed?

**Comment by Endofdays2018** [comment]
WhatsApp, Skype and FB Messenger. But this never caused an issued before

**Comment by HungryFeline** [comment]
Got a similar problem since a few days, but only with WhatsApp, ICQ still works. I tried restarting Franz, emptying the cache and even re-adding the service. OS is also Windows 10 (v1709), notification not even shown in the system tray. Franz is v4.0.4 - probably unsupported now? I'd upgrade, but it runs without an account.

**Comment by haraldox** [comment]
@HungryFeline Whatsapp has issued an update which unfortunately breaks Franz 4. Only Franz 5 is officially supported, where the update has already been hotfixed! :)

**Comment by haraldox** [comment]
@Endofdays2018 are you receiving notifications after yesterday's hotfix?

**Comment by Endofdays2018** [comment]
@haraldox yes, working now. thx!

**Comment by HungryFeline** [comment]
Yep, working. Thank you. Franz 5 also looks a lot nicer.

**Comment by geekyPrash** [comment]
I have recently started using Franz. And I am having trouble in getting notification on taskbar. Am I missing anything?

I see a red dot on notification area (system tray), but there is no highlight or indicator on taskbar.

Franz version: 5.0.0-beta.18 
Release: 1.8.4 / win32 / x64
OS: Windows 10
Services added: Hangouts (2 accounts)

**Comment by alekseysshubin** [comment]
I have the same problem, there is system tray notification but no notification on taskbar.
Franz 5.0.0-beta.18, Windows 10, Slack.

I've experimented a bit and found that the taskbar notification appears only when Franz isn't minimized. It doesn't depend on "Minimize to system tray" option, even if it's disabled and I use minimize window button "_" (not close button), the taskbar notification stops working.

**Comment by kmgalanakis** [comment]
I'm experiencing the same problem with Franz 5.0.0-beta.18, Windows 10 for both Skype and Whatsapp. Any chance that this getting fixed?

**Comment by DarthSonic** [comment]
> Same thing here for both Slack and WhatsApp. I'm getting the system tray notification (even when disabled) but I'm not getting taskbar notification.
> Also... Neither inside Franz it's showing the red dot notification on the services that do have new messages.

Same problem here in Win 10. No notifications in systray, info center or in app icons. Sounds are playing.

**Comment by ricfwolff** [comment]
> 
> Same problem here in Win 10. No notifications in systray, info center or in app icons. Sounds are playing.

Mine was fixed after latest update to version 5.0.0-beta.22.

**Comment by DarthSonic** [comment]
Mmh... I can not really tell when notifcations do not work but my guess is, that when I minimzed app to systray notifications will not work and no badge is shown in systray. When app is minimized both seem to work.

**Comment by pedromls** [comment]
I have Franz 5.0.0-beta.22 and win 7 pro 64 bits. Notifications do not work too. I have Franz in two other computers and work fine on them. I have Franz on the taskbar. I've already uninstalled and reinstalled Franz but the problem remains.
Any help ?
